spring:
  profiles:
    active: ${car.project.profile:local}


bugatti:
  engine:
    realtime:
      on-off: true
    topic-subscription:
      on-off: true
    mass:
      on-off: true

server:
  port: 8888