spring:
  datasource:
    url: jdbc:h2:mem:engine
    driver-class-name: org.h2.Driver
    data-username: sa
    password:

bugatti:
  engine:
    realtime:
      core-pool-size: 160
      max-pool-size: 180
      queue-capacity: 200
      on-off: true
    topic-subscription:
      core-pool-size: 240
      max-pool-size: 270
      queue-capacity: 300
      on-off: true

logging:
  level:
    org.apache: FATAL
    org.springframework: INFO
    com.example.bugatti: DEBUG
    com.example: INFO